#!/usr/bin/env bash
# command to show short name commit ids, date, time, and subject
#git log --abbrev-commit --pretty=format="%h %cs %s"
git log --pretty='format:%cd %s' --date=format:'%Y-%m-%d %H:%M:%S'
